#+title: 05 词汇语法

* 词汇语法

开始完整介绍C语言之前我们先来解释代码中的词汇语法和词汇单位。编程语言的词汇单位是一种记号(/tokens/)。
本章涵盖除常量意外的所有记号，常量将在后续章节讨论。记号一个最重要的用途是作为标识符--任何类型的名称。

** 用英语写程序

理论上你可以使用任何人类的语言书写C语言程序中的函数、变量和注释。C语言允许在注释中使用任意字符集，并且
你可以把非ASCII的字符放到有特殊前缀的标识符中。然而,考虑到现如今所有国家的程序员都都有可能参与程序开发
的情况最好使用英语来书写标识符和注释以便大家可以共同理解和开发程序。

英语是在所有国家的程序员中的通用的语言。如果代码以英语书写那么不论其他程序员是在孟加拉、比利时、玻利维亚、
巴西、还是保加利亚他们都可以理解。这些国家的多数程序员都可以说英语或者至少阅读它，但是他们并不能理解他们
彼此国家的语言。在印度存在很多种语言，也许两个印度程序员之间除了英语以外没有其他可以共同理解的语言。

如果你对书写英文没有信心那就尽力而为，并且同时在英文注释后面有你熟悉的语言写一个更好的版本并注明需要别人
将其翻译成英语，最终总会有人来做这件事。

程序的用户界面是另一个的问题。我们不能在用户界面上只使用一种语言，应该提供多种语言以供用户选择。这就需要
对程序进行本地化。(gettext软件包为此而生；详情见：[[https://www.gnu.org/software/libc/manual/html_mono/libc.html#Message-Translation][The GNU C Library]])之后，基于社区的翻译工作可以为用户
想要使用的所有语言提供翻译工作。

** 字符

GNU C 源代码通常使用1960年代为英语定义的[[https://en.wikipedia.org/wiki/ASCII][ASCII]]字符集。然而，同样可以使用[[https://en.wikipedia.org/wiki/UTF-8][UTF-8]]多字节编码的Unicode字符集。
这样就可以显示有重音符号的字母例如：‘á’，以及例如阿拉伯字符，汉字，西里尔字符，希伯来字符，日语字符和汉语字符。

在C语言代码中，非ASCII字符仅在注释、宽字符常量和字符串常量中合法。

另一种在常量（字符或字符串）和标识符中指定非ASCII字符的方法是使用以反斜杠开始的转义序列，指定预期的Unicode字符。
(详情见统一编码字符章节)这就指定了非ASCII字符，而不需要在源文件中放置一个真正的非ASCII字符。

对于某些特定字符的C语言也允许使用一种被称作二合字符的双字符代替。详情见双字符章节。
